settings:
  application:
    mode: release
    host: 0.0.0.0
    name: Hello GoOwl!
    port: 1234
  workspace:
    path: 
    repo:
      -
        id: 1 
        type: gogs
        trigger: ['push']
        repoaddr: 
        username: 
        password: 
        buildscript: 
        branch: master
      -
        id: 2 
        type: gogs
        trigger: ['push']
        repoaddr: 
        sshkeyaddr: 
        buildscript: 
        branch: master
      -
        id: 3
        type: github
        trigger: ['push']
        repoaddr: 
        token: 
        buildscript: 
        branch: main